from typing import Dict

STRINGS = {
    "en": {
        "welcome": "Welcome to RideShield. We're on the road with you, protecting your earnings every mile. 🚀\nYour income protection starts here.",
        "lang_select": "How would you like to communicate with your safety partner? Choose a language:",
        "start_protection": "Start Protection",
        "check_status": "Check Status",
        "select_role": "Excellent. To build your custom shield, tell us about your work:",
        "role_rider": "Rider",
        "role_driver": "Driver",
        "role_delivery": "Delivery Partner",
        "select_hours": "How many hours do you dedicate to the road daily?",
        "hours_low": "<4 hrs",
        "hours_mid": "4–8 hrs",
        "hours_high": "8+ hrs",
        "onboarding_complete": "Shield design complete! To activate your protection, just finish the final setup in the app 👇",
        "open_app": "Open RideShield",
        "status_header": "Your Security Status:",
        "status_active": "✅ Active & Protected",
        "status_pending": "⏳ Pending Final Setup",
        "status_inactive": "❌ Inactive",
        "coverage": "Coverage Limit",
        "risk_level": "Risk Level",
        "stay_safe": "Stay safe out there. We’ve got your back. 💚",
        "risk_detected_prefix": "⚠️ High-risk area detected",
        "risk_detected_body": "Drive carefully in {zone}. High risk conditions detected. We’re monitoring your safety.",
        "proactive_covered": "🌧️ Nature is unpredictable, but your income isn't. {trigger} detected—your coverage is ACTIVE. Stay safe! 💚",
        "claim_triggered": "🚨 Incident detected. Your protection is working—we've automatically initiated your claim. No action needed.",
        "payout_done": "💰 ₹{amount} has been secured for you. Your protection worked. Stay strong and safe 💚",
        "onboard_name": "A hero on the road! Let's get you protected.\n\nFirst, may we have your full name?",
        "onboard_city": "Nice to meet you, {name}! Which city do you primarily work in?",
        "onboard_platform": "Excellent. Which platform do you primarily partner with?",
        "onboard_plan_desc": "Based on your location and risk profile, here are your premium protection options:",
        "plan_select": "{plan}: ₹{price}",
        "checkout_msg": "Final step to secure your earnings! To activate your {plan} protection for this week, please complete this secure payment of ₹{price}. 🛡️",
        "pay_now": "Complete Payment",
        "pay_success": "✅ Payment Successful!\n\nWelcome to RideShield, {name}. Your earnings are now SECURED and your protection is ACTIVE.\n\nUsername: {phone}\nPassword: {password}\n(Change this in the app for security)",
    },
    "hi": {
        "welcome": "RideShield में आपका स्वागत है। हम हर मोड़ पर आपके साथ हैं, आपकी मेहनत की कमाई की रक्षा करने के लिए। 🚀",
        "lang_select": "आप अपने सुरक्षा साथी से किस भाषा में बात करना चाहेंगे? कृपया चुनें:",
        "start_protection": "सुरक्षा शुरू करें",
        "check_status": "स्थिति जांचें",
        "select_role": "बहुत बढ़िया। आपका सुरक्षा कवच तैयार करने के लिए, हमें अपने काम के बारे में बताएं:",
        "role_rider": "राइडर",
        "role_driver": "ड्राइवर",
        "role_delivery": "डिलीवरी पार्टनर",
        "select_hours": "आप रोजाना सड़कों पर कितने घंटे समर्पित करते हैं?",
        "hours_low": "<4 घंटे",
        "hours_mid": "4–8 घंटे",
        "hours_high": "8+ घंटे",
        "onboarding_complete": "कवच तैयार है! अपनी सुरक्षा सक्रिय करने के लिए बस ऐप में अंतिम सेटअप पूरा करें 👇",
        "open_app": "ऐप खोलें",
        "status_header": "आपकी सुरक्षा स्थिति:",
        "status_active": "✅ सक्रिय और सुरक्षित",
        "status_pending": "⏳ सेटअप लंबित है",
        "status_inactive": "❌ निष्क्रिय",
        "coverage": "कवरेज सीमा",
        "risk_level": "जोखिम स्तर",
        "stay_safe": "सुरक्षित रहें। हम हमेशा आपके साथ हैं। 💚",
        "risk_detected_prefix": "⚠️ उच्च-जोखिम वाला क्षेत्र पाया गया",
        "risk_detected_body": "⚠️ {zone} में सावधानी बरतें: उच्च जोखिम वाली स्थिति देखी गई है। सुरक्षित ड्राइव करें—RideShield आपकी सुरक्षा पर नज़र रखे हुए है।",
        "proactive_covered": "🌧️ मौसम का मिजाज बदल सकता है, लेकिन आपकी आय नहीं। {trigger} का पता चला है—आपकी सुरक्षा सक्रिय है। सुरक्षित रहें! 💚",
        "claim_triggered": "🚨 एक घटना का पता चला है। आपकी सुरक्षा सक्रिय है—हमने आपके दावे (claim) की प्रक्रिया शुरू कर दी है। आपको किसी कार्रवाई की आवश्यकता नहीं है।",
        "payout_done": "💰 ₹{amount} आपके खाते में सुरक्षित कर दिए गए हैं। आपकी सुरक्षा ने काम किया। मजबूत और सुरक्षित रहें 💚",
        "onboard_name": "सड़कों के असली हीरो! आइए आपकी सुरक्षा सुनिश्चित करते हैं।\n\nसबसे पहले, क्या हम आपका पूरा नाम जान सकते हैं?",
        "onboard_city": "आपसे मिलकर अच्छा लगा, {name}! आप मुख्य रूप से किस शहर में काम करते हैं?",
        "onboard_platform": "शानदार। आप किस प्लेटफॉर्म के साथ मुख्य रूप से काम करते हैं?",
        "onboard_plan_desc": "आपके स्थान और जोखिम के आधार पर, यहाँ आपके लिए प्रीमियम सुरक्षा विकल्प दिए गए हैं:",
        "plan_select": "{plan}: ₹{price}",
        "checkout_msg": "अपनी साप्ताहिक कमाई सुरक्षित करने का आखिरी कदम! अपनी {plan} सुरक्षा सक्रिय करने के लिए, कृपया ₹{price} का सुरक्षित भुगतान पूरा करें। 🛡️",
        "pay_now": "भुगतान पूरा करें",
        "pay_success": "✅ भुगतान सफल!\n\nRideShield में आपका स्वागत है, {name}। आपकी कमाई अब सुरक्षित है और आपकी सुरक्षा सक्रिय है।\n\nयूज़रनेम: {phone}\nपासवर्ड: {password}\n(सुरक्षा के लिए इसे ऐप में बदल लें)",
    }
}

def get_string(key: str, lang: str = "en", **kwargs) -> str:
    """Get a localized string, falling back to English if Hindi is missing."""
    text = STRINGS.get(lang, STRINGS["en"]).get(key, STRINGS["en"].get(key, key))
    return text.format(**kwargs)
