from typing import Dict

STRINGS = {
    "en": {
        "welcome": "Welcome to RideShield 🚀\nYour income protection starts here.",
        "lang_select": "Please select your preferred language:",
        "start_protection": "Start Protection",
        "check_status": "Check Status",
        "select_role": "Let’s get you protected. What do you do?",
        "role_rider": "Rider",
        "role_driver": "Driver",
        "role_delivery": "Delivery Partner",
        "select_hours": "How many hours do you work daily?",
        "hours_low": "<4 hrs",
        "hours_mid": "4–8 hrs",
        "hours_high": "8+ hrs",
        "onboarding_complete": "Almost done. Complete onboarding in the app to activate protection 👇",
        "open_app": "Open App",
        "status_header": "Your Protection Status:",
        "status_active": "✅ Active",
        "status_pending": "⏳ Pending Onboarding",
        "status_inactive": "❌ Inactive",
        "coverage": "Coverage",
        "risk_level": "Risk Level",
        "stay_safe": "Stay safe out there 💚",
        "risk_detected_prefix": "⚠️ High-risk area detected",
        "risk_detected_body": "Drive carefully in {zone}. We’re monitoring your safety.",
        "proactive_covered": "🌧️ Possible {trigger} detected, but you are covered! Your protection is active.",
        "claim_triggered": "🚨 Incident detected. We’ve initiated your claim. No action needed.",
        "payout_done": "💰 ₹{amount} credited. Your protection worked. Stay strong 💚",
        "onboard_name": "Great Choice! Let's get you protected.\n\nFirst, what is your full name?",
        "onboard_city": "Nice to meet you, {name}! Which city do you work in?",
        "onboard_platform": "Awesome. Which platform do you primarily work for?",
        "onboard_plan_desc": "Based on your location, here are your weekly protection options:",
        "plan_select": "Select {plan} (₹{price})",
        "checkout_msg": "You're nearly there! To activate your {plan} protection for this week, please complete the payment of ₹{price}.",
        "pay_now": "Pay Now (Mock)",
        "pay_success": "✅ Payment Successful!\n\nWelcome to RideShield, {name}. Your protection is now ACTIVE.\n\nUsername: {phone}\nPassword: {password}\n(Change this in the app)",
    },
    "hi": {
        "welcome": "RideShield में आपका स्वागत है 🚀\nआपकी आय की सुरक्षा यहीं से शुरू होती है।",
        "lang_select": "अपनी पसंदीदा भाषा चुनें:",
        "start_protection": "सुरक्षा शुरू करें",
        "check_status": "स्थिति जांचें",
        "select_role": "आइए आपकी सुरक्षा शुरू करें। आप क्या काम करते हैं?",
        "role_rider": "राइडर",
        "role_driver": "ड्राइवर",
        "role_delivery": "डिलीवरी पार्टनर",
        "select_hours": "आप रोजाना कितने घंटे काम करते हैं?",
        "hours_low": "<4 घंटे",
        "hours_mid": "4–8 घंटे",
        "hours_high": "8+ घंटे",
        "onboarding_complete": "लगभग पूरा हो गया। सुरक्षा सक्रिय करने के लिए ऐप में ऑनबोर्डिंग पूरी करें 👇",
        "open_app": "ऐप खोलें",
        "status_header": "आपकी सुरक्षा स्थिति:",
        "status_active": "✅ सक्रिय",
        "status_pending": "⏳ ऑनबोर्डिंग लंबित",
        "status_inactive": "❌ निष्क्रिय",
        "coverage": "कवरेज",
        "risk_level": "जोखिम स्तर",
        "stay_safe": "सुरक्षित रहें 💚",
        "risk_detected_prefix": "⚠️ उच्च-जोखिम वाला क्षेत्र पाया गया",
        "risk_detected_body": "{zone} में सावधानी से ड्राइव करें। हम आपकी सुरक्षा की निगरानी कर रहे हैं।",
        "proactive_covered": "🌧️ संभव {trigger} पाया गया, लेकिन आप सुरक्षित हैं! आपकी सुरक्षा सक्रिय है।",
        "claim_triggered": "🚨 घटना का पता चला। हमने आपके दावे की प्रक्रिया शुरू कर दी है। किसी कार्रवाई की आवश्यकता नहीं है।",
        "payout_done": "💰 ₹{amount} जमा किया गया। आपकी सुरक्षा ने काम किया। मजबूत रहें 💚",
        "onboard_name": "बेहतरीन विकल्प! आइए आपको सुरक्षित करते हैं।\n\nसबसे पहले, आपका पूरा नाम क्या है?",
        "onboard_city": "आपसे मिलकर अच्छा लगा, {name}! आप किस शहर में काम करते हैं?",
        "onboard_platform": "बहुत बढ़िया। आप मुख्य रूप से किस प्लेटफॉर्म के लिए काम करते हैं?",
        "onboard_plan_desc": "आपके स्थान के आधार पर, यहाँ आपके साप्ताहिक सुरक्षा विकल्प दिए गए हैं:",
        "plan_select": "{plan} चुनें (₹{price})",
        "checkout_msg": "आप बस पहुँचने ही वाले हैं! इस सप्ताह के लिए अपनी {plan} सुरक्षा को सक्रिय करने के लिए, कृपया ₹{price} का भुगतान पूरा करें।",
        "pay_now": "अभी भुगतान करें (मॉक)",
        "pay_success": "✅ भुगतान सफल!\n\nRideShield में आपका स्वागत है, {name}। आपकी सुरक्षा अब सक्रिय है।\n\nयूजरनाम: {phone}\nपासवर्ड: {password}\n(इसे ऐप में बदलें)",
    }
}

def get_string(key: str, lang: str = "en", **kwargs) -> str:
    """Get a localized string, falling back to English if Hindi is missing."""
    text = STRINGS.get(lang, STRINGS["en"]).get(key, STRINGS["en"].get(key, key))
    return text.format(**kwargs)
