"""add_simulation_isolation_columns

Revision ID: 5e5426f51627
Revises: 006
Create Date: 2026-04-14 03:00:49.587849
"""
from alembic import op
import sqlalchemy as sa


revision = '5e5426f51627'
down_revision = '006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'events', 'zones', ['zone_id'], ['id'])
    op.add_column('fraud_logs', sa.Column('is_simulated', sa.Boolean(), nullable=True))
    op.add_column('fraud_logs', sa.Column('simulation_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_fraud_logs_is_simulated'), 'fraud_logs', ['is_simulated'], unique=False)
    op.add_column('worker_activity', sa.Column('is_simulated', sa.Boolean(), nullable=True))
    op.add_column('worker_activity', sa.Column('simulation_type', sa.String(length=50), nullable=True))
    op.create_index('idx_activity_simulated', 'worker_activity', ['is_simulated'], unique=False)
    op.create_index(op.f('ix_worker_activity_is_simulated'), 'worker_activity', ['is_simulated'], unique=False)
    op.create_foreign_key(None, 'worker_activity', 'zones', ['zone_id'], ['id'])
    op.create_foreign_key(None, 'workers', 'cities', ['city_id'], ['id'])
    op.create_foreign_key(None, 'workers', 'zones', ['zone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workers', type_='foreignkey')
    op.drop_constraint(None, 'workers', type_='foreignkey')
    op.drop_constraint(None, 'worker_activity', type_='foreignkey')
    op.drop_index(op.f('ix_worker_activity_is_simulated'), table_name='worker_activity')
    op.drop_index('idx_activity_simulated', table_name='worker_activity')
    op.drop_column('worker_activity', 'simulation_type')
    op.drop_column('worker_activity', 'is_simulated')
    op.drop_index(op.f('ix_fraud_logs_is_simulated'), table_name='fraud_logs')
    op.drop_column('fraud_logs', 'simulation_type')
    op.drop_column('fraud_logs', 'is_simulated')
    op.drop_constraint(None, 'events', type_='foreignkey')
    # ### end Alembic commands ###
